---
title: "grace_analysis"
format: html
---

load packages

```{r}
library(bayesrules)
library(dplyr)
library(rstanarm)
library(bayesplot)
library(tidyverse)
library(tidybayes)
library(broom.mixed)
library(ggpubr)
```

load data

```{r}
diabetes <- read.csv("data/diabetes_data.csv")
#hyper <- read.csv("data/hypertension_data.csv")
#stroke <- read.csv("data/stroke_data.csv")

head(diabetes)
```

\*\*kaggle data is already cleaned

making model

```{r}
#convert outcome (high bp) variable to factor
diabetes$HighBP <- as.factor(diabetes$HighBP)

#model
diabetes_model <- stan_glm(
  HighBP ~ Diabetes + HighChol + BMI + CholCheck +
    Age + Sex + Smoker + HeartDiseaseorAttack + PhysActivity + Stroke + HvyAlcoholConsump,
  data = diabetes,
  family = binomial(link = "logit"),
  prior = normal(0, 1, autoscale = TRUE),
  prior_intercept = normal(0, 2),
  chains = 4,
  iter = 1000,
  seed = 84735
)
```

```{r}
#save model so no need reload later
#saveRDS(diabetes_model, "diabetes_model.rds")

#load model
diabetes_model <- readRDS("diabetes_model.rds")

summary(diabetes_model)
```

```{r}
plot(diabetes_model, prob = 0.95)

```

```{r}
posterior_interval(diabetes_model, prob = 0.9)
posterior_interval(diabetes_model, prob = 0.95)

```

```{r}
pp_check(diabetes_model)
```

```{r}
exp(posterior_interval(diabetes_model, prob = 0.80))
```

```{r}
posterior <- as.array(diabetes_model)
mcmc_areas(posterior, 
           pars = c("Diabetes", "HighChol", "BMI", "Age", "Sex"),
           prob = 0.95)

```

```{r}
mcmc_trace(posterior, pars = c("Diabetes", "HighChol", "BMI"))
```

```{r}
pred_probs <- posterior_linpred(diabetes_model, transform = TRUE)
p_mean <- colMeans(pred_probs)
pred_class <- ifelse(p_mean > 0.5, 1, 0)
mean(pred_class == diabetes$HighBP)

```

```{r}
pp_check(diabetes_model, type = "stat", stat = "mean")

```
